services:
  azdevops-agent:
    build: .
    image: azdevopsdeploymentagent:1.0
    container_name: azdevops-agent
    restart: always
    volumes:
      - deploymentdevagent:/azagent
    env_file:
      - ./prod.env

volumes:
  deploymentdevagent:
    external: true
