version: '3.9'

services:
  azdevops-agent:
    build: .
    container_name: azdevops-agent
    restart: always
    volumes:
      - volumea:/azagent
    env_file:
      - prod.env
    command: ["/bin/bash", "/deployagent.sh"]

volumes:
  volumea:
    external: true
